// import { useState,useEffect } from "react";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
//   const [isHydrated, setIsHydrated] = useState(false);

//   // Ensure this only runs on the client to prevent SSR mismatch
//   useEffect(() => {
//     setIsHydrated(true);
//   }, []);

//   if (!isHydrated) {
//     return null;
//   }
  return (
    <html lang="en">
      <body>
       <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
